### ISSUE TITLE
How to edit icon colors?

### ISSUE THREAD

**Issue by KTsarlz** [jeselxe/tool-bar-atom#14]
I want to know to edit the colors of the icon..

**Comment by jeselxe** [comment]
You can Override the styles in your Atom Stylesheet (Atom -> Stylesheet...):

```css
.tool-bar button.tool-bar-btn {
    color: red;
}
```
